services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: docker/images/n8n-custom/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: WEBHOOK_TUNNEL_URL
        sync: false
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: database
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromService:
          type: database
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: database
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromService:
          type: database
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: database
          name: n8n-db
          property: password
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: GENERIC_TIMEZONE
        value: Asia/Ho_Chi_Minh

  - type: database
    name: n8n-db
    plan: starter
    properties:
      engine: postgres
      version: 15
